# Generated by Django 5.2 on 2025-04-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
