# Generated by Django 5.2 on 2025-04-07 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_announcement_options_alter_mark_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
